### ISSUE TITLE
PROJECT NOT DONE

### ISSUE THREAD

**Issue by mxdavis** [tracypholmes/ehm_track#3]
Isn't this an issue?

**Comment by tracypholmes** [comment]
I agree @mxdavis - it is an issue. Working on it now!

**Comment by achasveachas** [comment]
Can confirm this issue on my machine as well.

**Comment by tracypholmes** [comment]
@mxdavis @achasveachas apologies for the delay - currently working on this issue as we speak.

**Comment by tracypholmes** [comment]
Anticipated completion 31 October 2017 @mxdavis @achasveachas

**Comment by achasveachas** [comment]
I believe we have enough of an MVP going that this issue can effectively be closed.

**Comment by tracypholmes** [comment]
project submitted; assessment scheduled. Closing!
